// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/home/likhon/Desktop/Personal Projects/seo-sage-v3/node_modules/.pnpm/@sidebase+nuxt-auth@0.9.3_magicast@0.3.5_next-auth@4.21.1_next@13.5.7_@babel+core@7.25.2_reac_6a546eyos76mppealed2kjiene/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
interface SessionData {
  id: string | number
}
}
