
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'OnboardingForm': typeof import("../components/OnboardingForm.vue")['default']
    'AgencyPanelSidebar': typeof import("../components/agency/AgencyPanelSidebar.vue")['default']
    'AgencyTopHeader': typeof import("../components/agency/AgencyTopHeader.vue")['default']
    'AgencyMiniSidebar': typeof import("../components/agency/MiniSidebar.vue")['default']
    'ForsvgAdditionalSearchTerms': typeof import("../components/forsvg/AdditionalSearchTerms.vue")['default']
    'ForsvgArrowDownIcon': typeof import("../components/forsvg/ArrowDownIcon.vue")['default']
    'ForsvgArrowLeftIcon': typeof import("../components/forsvg/ArrowLeftIcon.vue")['default']
    'ForsvgArrowRightIcon': typeof import("../components/forsvg/ArrowRightIcon.vue")['default']
    'ForsvgArrowUpIcon': typeof import("../components/forsvg/ArrowUpIcon.vue")['default']
    'ForsvgArrowUpRight': typeof import("../components/forsvg/ArrowUpRight.vue")['default']
    'ForsvgArticaleSuggset': typeof import("../components/forsvg/ArticaleSuggset.vue")['default']
    'ForsvgArticle3DotIcon': typeof import("../components/forsvg/Article3DotIcon.vue")['default']
    'ForsvgArticleCalenderPen': typeof import("../components/forsvg/ArticleCalenderPen.vue")['default']
    'ForsvgArticleChartLineUp': typeof import("../components/forsvg/ArticleChartLineUp.vue")['default']
    'ForsvgArticleDraftEditIcon': typeof import("../components/forsvg/ArticleDraftEditIcon.vue")['default']
    'ForsvgArticleEditIcon': typeof import("../components/forsvg/ArticleEditIcon.vue")['default']
    'ForsvgArticleIcon': typeof import("../components/forsvg/ArticleIcon.vue")['default']
    'ForsvgArticleSuggestionIcon': typeof import("../components/forsvg/ArticleSuggestionIcon.vue")['default']
    'ForsvgArticleThumbUp': typeof import("../components/forsvg/ArticleThumbUp.vue")['default']
    'ForsvgArticleUserCheck': typeof import("../components/forsvg/ArticleUserCheck.vue")['default']
    'ForsvgAscendingIcon': typeof import("../components/forsvg/AscendingIcon.vue")['default']
    'ForsvgAveragePosition': typeof import("../components/forsvg/AveragePosition.vue")['default']
    'ForsvgBellIcon': typeof import("../components/forsvg/BellIcon.vue")['default']
    'ForsvgBluebtnSpinner': typeof import("../components/forsvg/BluebtnSpinner.vue")['default']
    'ForsvgBook': typeof import("../components/forsvg/Book.vue")['default']
    'ForsvgCircleProgress': typeof import("../components/forsvg/CircleProgress.vue")['default']
    'ForsvgCircleThreeQuartersStroke': typeof import("../components/forsvg/CircleThreeQuartersStroke.vue")['default']
    'ForsvgCross': typeof import("../components/forsvg/Cross.vue")['default']
    'ForsvgDashboardIcon': typeof import("../components/forsvg/DashboardIcon.vue")['default']
    'ForsvgDeleteIcon': typeof import("../components/forsvg/DeleteIcon.vue")['default']
    'ForsvgDescendingIcon': typeof import("../components/forsvg/DescendingIcon.vue")['default']
    'ForsvgDownCaret': typeof import("../components/forsvg/DownCaret.vue")['default']
    'ForsvgDownDrodown': typeof import("../components/forsvg/DownDrodown.vue")['default']
    'ForsvgEditIcon': typeof import("../components/forsvg/EditIcon.vue")['default']
    'ForsvgGenerateText': typeof import("../components/forsvg/GenerateText.vue")['default']
    'ForsvgHeaderLogo': typeof import("../components/forsvg/HeaderLogo.vue")['default']
    'ForsvgKeywords': typeof import("../components/forsvg/Keywords.vue")['default']
    'ForsvgLoginBg': typeof import("../components/forsvg/LoginBg.vue")['default']
    'ForsvgMainSearchTerms': typeof import("../components/forsvg/MainSearchTerms.vue")['default']
    'ForsvgMenuBar': typeof import("../components/forsvg/MenuBar.vue")['default']
    'ForsvgMyBlueBtnSpinner': typeof import("../components/forsvg/MyBlueBtnSpinner.vue")['default']
    'ForsvgPaperClip': typeof import("../components/forsvg/PaperClip.vue")['default']
    'ForsvgPlusIcon': typeof import("../components/forsvg/PlusIcon.vue")['default']
    'ForsvgQuestionMark': typeof import("../components/forsvg/QuestionMark.vue")['default']
    'ForsvgReasoning': typeof import("../components/forsvg/Reasoning.vue")['default']
    'ForsvgReportIcon': typeof import("../components/forsvg/ReportIcon.vue")['default']
    'ForsvgRightArrowGo': typeof import("../components/forsvg/RightArrowGo.vue")['default']
    'ForsvgRocketBlack': typeof import("../components/forsvg/RocketBlack.vue")['default']
    'ForsvgRocketIcon': typeof import("../components/forsvg/RocketIcon.vue")['default']
    'ForsvgSageSunglasses': typeof import("../components/forsvg/SageSunglasses.vue")['default']
    'ForsvgSearch': typeof import("../components/forsvg/Search.vue")['default']
    'ForsvgSeoToolIcon': typeof import("../components/forsvg/SeoToolIcon.vue")['default']
    'ForsvgSetting': typeof import("../components/forsvg/Setting.vue")['default']
    'ForsvgSpinningWheel': typeof import("../components/forsvg/SpinningWheel.vue")['default']
    'ForsvgStar': typeof import("../components/forsvg/Star.vue")['default']
    'ForsvgSummary': typeof import("../components/forsvg/Summary.vue")['default']
    'ForsvgTbjIcon': typeof import("../components/forsvg/TbjIcon.vue")['default']
    'ForsvgThumbsUp': typeof import("../components/forsvg/ThumbsUp.vue")['default']
    'ForsvgThumbsUpSolid': typeof import("../components/forsvg/ThumbsUpSolid.vue")['default']
    'ForsvgTotalImpressions': typeof import("../components/forsvg/TotalImpressions.vue")['default']
    'ForsvgTrafficSource': typeof import("../components/forsvg/TrafficSource.vue")['default']
    'ForsvgTwitter': typeof import("../components/forsvg/Twitter.vue")['default']
    'ForsvgUpColor': typeof import("../components/forsvg/UpColor.vue")['default']
    'ForsvgBookMarkBlank': typeof import("../components/forsvg/bookMarkBlank.vue")['default']
    'ForsvgBookMarkFill': typeof import("../components/forsvg/bookMarkFill.vue")['default']
    'ForsvgClose': typeof import("../components/forsvg/close.vue")['default']
    'ForsvgDelete': typeof import("../components/forsvg/delete.vue")['default']
    'ForsvgDownArrow': typeof import("../components/forsvg/downArrow.vue")['default']
    'ForsvgDownBlank': typeof import("../components/forsvg/downBlank.vue")['default']
    'ForsvgDownFill': typeof import("../components/forsvg/downFill.vue")['default']
    'ForsvgFeedBack': typeof import("../components/forsvg/feedBack.vue")['default']
    'ForsvgGetKeyword': typeof import("../components/forsvg/getKeyword.vue")['default']
    'ForsvgKeywordResearch': typeof import("../components/forsvg/keywordResearch.vue")['default']
    'ForsvgLeftArrow': typeof import("../components/forsvg/leftArrow.vue")['default']
    'ForsvgNotes': typeof import("../components/forsvg/notes.vue")['default']
    'ForsvgPlus': typeof import("../components/forsvg/plus.vue")['default']
    'ForsvgPlusAi': typeof import("../components/forsvg/plusAi.vue")['default']
    'ForsvgQsnMark': typeof import("../components/forsvg/qsnMark.vue")['default']
    'ForsvgRightArrow': typeof import("../components/forsvg/rightArrow.vue")['default']
    'ForsvgUpBlank': typeof import("../components/forsvg/upBlank.vue")['default']
    'ForsvgUpFill': typeof import("../components/forsvg/upFill.vue")['default']
    'ForsvgWorldBlack': typeof import("../components/forsvg/worldBlack.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyOnboardingForm': typeof import("../components/OnboardingForm.vue")['default']
    'LazyAgencyPanelSidebar': typeof import("../components/agency/AgencyPanelSidebar.vue")['default']
    'LazyAgencyTopHeader': typeof import("../components/agency/AgencyTopHeader.vue")['default']
    'LazyAgencyMiniSidebar': typeof import("../components/agency/MiniSidebar.vue")['default']
    'LazyForsvgAdditionalSearchTerms': typeof import("../components/forsvg/AdditionalSearchTerms.vue")['default']
    'LazyForsvgArrowDownIcon': typeof import("../components/forsvg/ArrowDownIcon.vue")['default']
    'LazyForsvgArrowLeftIcon': typeof import("../components/forsvg/ArrowLeftIcon.vue")['default']
    'LazyForsvgArrowRightIcon': typeof import("../components/forsvg/ArrowRightIcon.vue")['default']
    'LazyForsvgArrowUpIcon': typeof import("../components/forsvg/ArrowUpIcon.vue")['default']
    'LazyForsvgArrowUpRight': typeof import("../components/forsvg/ArrowUpRight.vue")['default']
    'LazyForsvgArticaleSuggset': typeof import("../components/forsvg/ArticaleSuggset.vue")['default']
    'LazyForsvgArticle3DotIcon': typeof import("../components/forsvg/Article3DotIcon.vue")['default']
    'LazyForsvgArticleCalenderPen': typeof import("../components/forsvg/ArticleCalenderPen.vue")['default']
    'LazyForsvgArticleChartLineUp': typeof import("../components/forsvg/ArticleChartLineUp.vue")['default']
    'LazyForsvgArticleDraftEditIcon': typeof import("../components/forsvg/ArticleDraftEditIcon.vue")['default']
    'LazyForsvgArticleEditIcon': typeof import("../components/forsvg/ArticleEditIcon.vue")['default']
    'LazyForsvgArticleIcon': typeof import("../components/forsvg/ArticleIcon.vue")['default']
    'LazyForsvgArticleSuggestionIcon': typeof import("../components/forsvg/ArticleSuggestionIcon.vue")['default']
    'LazyForsvgArticleThumbUp': typeof import("../components/forsvg/ArticleThumbUp.vue")['default']
    'LazyForsvgArticleUserCheck': typeof import("../components/forsvg/ArticleUserCheck.vue")['default']
    'LazyForsvgAscendingIcon': typeof import("../components/forsvg/AscendingIcon.vue")['default']
    'LazyForsvgAveragePosition': typeof import("../components/forsvg/AveragePosition.vue")['default']
    'LazyForsvgBellIcon': typeof import("../components/forsvg/BellIcon.vue")['default']
    'LazyForsvgBluebtnSpinner': typeof import("../components/forsvg/BluebtnSpinner.vue")['default']
    'LazyForsvgBook': typeof import("../components/forsvg/Book.vue")['default']
    'LazyForsvgCircleProgress': typeof import("../components/forsvg/CircleProgress.vue")['default']
    'LazyForsvgCircleThreeQuartersStroke': typeof import("../components/forsvg/CircleThreeQuartersStroke.vue")['default']
    'LazyForsvgCross': typeof import("../components/forsvg/Cross.vue")['default']
    'LazyForsvgDashboardIcon': typeof import("../components/forsvg/DashboardIcon.vue")['default']
    'LazyForsvgDeleteIcon': typeof import("../components/forsvg/DeleteIcon.vue")['default']
    'LazyForsvgDescendingIcon': typeof import("../components/forsvg/DescendingIcon.vue")['default']
    'LazyForsvgDownCaret': typeof import("../components/forsvg/DownCaret.vue")['default']
    'LazyForsvgDownDrodown': typeof import("../components/forsvg/DownDrodown.vue")['default']
    'LazyForsvgEditIcon': typeof import("../components/forsvg/EditIcon.vue")['default']
    'LazyForsvgGenerateText': typeof import("../components/forsvg/GenerateText.vue")['default']
    'LazyForsvgHeaderLogo': typeof import("../components/forsvg/HeaderLogo.vue")['default']
    'LazyForsvgKeywords': typeof import("../components/forsvg/Keywords.vue")['default']
    'LazyForsvgLoginBg': typeof import("../components/forsvg/LoginBg.vue")['default']
    'LazyForsvgMainSearchTerms': typeof import("../components/forsvg/MainSearchTerms.vue")['default']
    'LazyForsvgMenuBar': typeof import("../components/forsvg/MenuBar.vue")['default']
    'LazyForsvgMyBlueBtnSpinner': typeof import("../components/forsvg/MyBlueBtnSpinner.vue")['default']
    'LazyForsvgPaperClip': typeof import("../components/forsvg/PaperClip.vue")['default']
    'LazyForsvgPlusIcon': typeof import("../components/forsvg/PlusIcon.vue")['default']
    'LazyForsvgQuestionMark': typeof import("../components/forsvg/QuestionMark.vue")['default']
    'LazyForsvgReasoning': typeof import("../components/forsvg/Reasoning.vue")['default']
    'LazyForsvgReportIcon': typeof import("../components/forsvg/ReportIcon.vue")['default']
    'LazyForsvgRightArrowGo': typeof import("../components/forsvg/RightArrowGo.vue")['default']
    'LazyForsvgRocketBlack': typeof import("../components/forsvg/RocketBlack.vue")['default']
    'LazyForsvgRocketIcon': typeof import("../components/forsvg/RocketIcon.vue")['default']
    'LazyForsvgSageSunglasses': typeof import("../components/forsvg/SageSunglasses.vue")['default']
    'LazyForsvgSearch': typeof import("../components/forsvg/Search.vue")['default']
    'LazyForsvgSeoToolIcon': typeof import("../components/forsvg/SeoToolIcon.vue")['default']
    'LazyForsvgSetting': typeof import("../components/forsvg/Setting.vue")['default']
    'LazyForsvgSpinningWheel': typeof import("../components/forsvg/SpinningWheel.vue")['default']
    'LazyForsvgStar': typeof import("../components/forsvg/Star.vue")['default']
    'LazyForsvgSummary': typeof import("../components/forsvg/Summary.vue")['default']
    'LazyForsvgTbjIcon': typeof import("../components/forsvg/TbjIcon.vue")['default']
    'LazyForsvgThumbsUp': typeof import("../components/forsvg/ThumbsUp.vue")['default']
    'LazyForsvgThumbsUpSolid': typeof import("../components/forsvg/ThumbsUpSolid.vue")['default']
    'LazyForsvgTotalImpressions': typeof import("../components/forsvg/TotalImpressions.vue")['default']
    'LazyForsvgTrafficSource': typeof import("../components/forsvg/TrafficSource.vue")['default']
    'LazyForsvgTwitter': typeof import("../components/forsvg/Twitter.vue")['default']
    'LazyForsvgUpColor': typeof import("../components/forsvg/UpColor.vue")['default']
    'LazyForsvgBookMarkBlank': typeof import("../components/forsvg/bookMarkBlank.vue")['default']
    'LazyForsvgBookMarkFill': typeof import("../components/forsvg/bookMarkFill.vue")['default']
    'LazyForsvgClose': typeof import("../components/forsvg/close.vue")['default']
    'LazyForsvgDelete': typeof import("../components/forsvg/delete.vue")['default']
    'LazyForsvgDownArrow': typeof import("../components/forsvg/downArrow.vue")['default']
    'LazyForsvgDownBlank': typeof import("../components/forsvg/downBlank.vue")['default']
    'LazyForsvgDownFill': typeof import("../components/forsvg/downFill.vue")['default']
    'LazyForsvgFeedBack': typeof import("../components/forsvg/feedBack.vue")['default']
    'LazyForsvgGetKeyword': typeof import("../components/forsvg/getKeyword.vue")['default']
    'LazyForsvgKeywordResearch': typeof import("../components/forsvg/keywordResearch.vue")['default']
    'LazyForsvgLeftArrow': typeof import("../components/forsvg/leftArrow.vue")['default']
    'LazyForsvgNotes': typeof import("../components/forsvg/notes.vue")['default']
    'LazyForsvgPlus': typeof import("../components/forsvg/plus.vue")['default']
    'LazyForsvgPlusAi': typeof import("../components/forsvg/plusAi.vue")['default']
    'LazyForsvgQsnMark': typeof import("../components/forsvg/qsnMark.vue")['default']
    'LazyForsvgRightArrow': typeof import("../components/forsvg/rightArrow.vue")['default']
    'LazyForsvgUpBlank': typeof import("../components/forsvg/upBlank.vue")['default']
    'LazyForsvgUpFill': typeof import("../components/forsvg/upFill.vue")['default']
    'LazyForsvgWorldBlack': typeof import("../components/forsvg/worldBlack.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const OnboardingForm: typeof import("../components/OnboardingForm.vue")['default']
export const AgencyPanelSidebar: typeof import("../components/agency/AgencyPanelSidebar.vue")['default']
export const AgencyTopHeader: typeof import("../components/agency/AgencyTopHeader.vue")['default']
export const AgencyMiniSidebar: typeof import("../components/agency/MiniSidebar.vue")['default']
export const ForsvgAdditionalSearchTerms: typeof import("../components/forsvg/AdditionalSearchTerms.vue")['default']
export const ForsvgArrowDownIcon: typeof import("../components/forsvg/ArrowDownIcon.vue")['default']
export const ForsvgArrowLeftIcon: typeof import("../components/forsvg/ArrowLeftIcon.vue")['default']
export const ForsvgArrowRightIcon: typeof import("../components/forsvg/ArrowRightIcon.vue")['default']
export const ForsvgArrowUpIcon: typeof import("../components/forsvg/ArrowUpIcon.vue")['default']
export const ForsvgArrowUpRight: typeof import("../components/forsvg/ArrowUpRight.vue")['default']
export const ForsvgArticaleSuggset: typeof import("../components/forsvg/ArticaleSuggset.vue")['default']
export const ForsvgArticle3DotIcon: typeof import("../components/forsvg/Article3DotIcon.vue")['default']
export const ForsvgArticleCalenderPen: typeof import("../components/forsvg/ArticleCalenderPen.vue")['default']
export const ForsvgArticleChartLineUp: typeof import("../components/forsvg/ArticleChartLineUp.vue")['default']
export const ForsvgArticleDraftEditIcon: typeof import("../components/forsvg/ArticleDraftEditIcon.vue")['default']
export const ForsvgArticleEditIcon: typeof import("../components/forsvg/ArticleEditIcon.vue")['default']
export const ForsvgArticleIcon: typeof import("../components/forsvg/ArticleIcon.vue")['default']
export const ForsvgArticleSuggestionIcon: typeof import("../components/forsvg/ArticleSuggestionIcon.vue")['default']
export const ForsvgArticleThumbUp: typeof import("../components/forsvg/ArticleThumbUp.vue")['default']
export const ForsvgArticleUserCheck: typeof import("../components/forsvg/ArticleUserCheck.vue")['default']
export const ForsvgAscendingIcon: typeof import("../components/forsvg/AscendingIcon.vue")['default']
export const ForsvgAveragePosition: typeof import("../components/forsvg/AveragePosition.vue")['default']
export const ForsvgBellIcon: typeof import("../components/forsvg/BellIcon.vue")['default']
export const ForsvgBluebtnSpinner: typeof import("../components/forsvg/BluebtnSpinner.vue")['default']
export const ForsvgBook: typeof import("../components/forsvg/Book.vue")['default']
export const ForsvgCircleProgress: typeof import("../components/forsvg/CircleProgress.vue")['default']
export const ForsvgCircleThreeQuartersStroke: typeof import("../components/forsvg/CircleThreeQuartersStroke.vue")['default']
export const ForsvgCross: typeof import("../components/forsvg/Cross.vue")['default']
export const ForsvgDashboardIcon: typeof import("../components/forsvg/DashboardIcon.vue")['default']
export const ForsvgDeleteIcon: typeof import("../components/forsvg/DeleteIcon.vue")['default']
export const ForsvgDescendingIcon: typeof import("../components/forsvg/DescendingIcon.vue")['default']
export const ForsvgDownCaret: typeof import("../components/forsvg/DownCaret.vue")['default']
export const ForsvgDownDrodown: typeof import("../components/forsvg/DownDrodown.vue")['default']
export const ForsvgEditIcon: typeof import("../components/forsvg/EditIcon.vue")['default']
export const ForsvgGenerateText: typeof import("../components/forsvg/GenerateText.vue")['default']
export const ForsvgHeaderLogo: typeof import("../components/forsvg/HeaderLogo.vue")['default']
export const ForsvgKeywords: typeof import("../components/forsvg/Keywords.vue")['default']
export const ForsvgLoginBg: typeof import("../components/forsvg/LoginBg.vue")['default']
export const ForsvgMainSearchTerms: typeof import("../components/forsvg/MainSearchTerms.vue")['default']
export const ForsvgMenuBar: typeof import("../components/forsvg/MenuBar.vue")['default']
export const ForsvgMyBlueBtnSpinner: typeof import("../components/forsvg/MyBlueBtnSpinner.vue")['default']
export const ForsvgPaperClip: typeof import("../components/forsvg/PaperClip.vue")['default']
export const ForsvgPlusIcon: typeof import("../components/forsvg/PlusIcon.vue")['default']
export const ForsvgQuestionMark: typeof import("../components/forsvg/QuestionMark.vue")['default']
export const ForsvgReasoning: typeof import("../components/forsvg/Reasoning.vue")['default']
export const ForsvgReportIcon: typeof import("../components/forsvg/ReportIcon.vue")['default']
export const ForsvgRightArrowGo: typeof import("../components/forsvg/RightArrowGo.vue")['default']
export const ForsvgRocketBlack: typeof import("../components/forsvg/RocketBlack.vue")['default']
export const ForsvgRocketIcon: typeof import("../components/forsvg/RocketIcon.vue")['default']
export const ForsvgSageSunglasses: typeof import("../components/forsvg/SageSunglasses.vue")['default']
export const ForsvgSearch: typeof import("../components/forsvg/Search.vue")['default']
export const ForsvgSeoToolIcon: typeof import("../components/forsvg/SeoToolIcon.vue")['default']
export const ForsvgSetting: typeof import("../components/forsvg/Setting.vue")['default']
export const ForsvgSpinningWheel: typeof import("../components/forsvg/SpinningWheel.vue")['default']
export const ForsvgStar: typeof import("../components/forsvg/Star.vue")['default']
export const ForsvgSummary: typeof import("../components/forsvg/Summary.vue")['default']
export const ForsvgTbjIcon: typeof import("../components/forsvg/TbjIcon.vue")['default']
export const ForsvgThumbsUp: typeof import("../components/forsvg/ThumbsUp.vue")['default']
export const ForsvgThumbsUpSolid: typeof import("../components/forsvg/ThumbsUpSolid.vue")['default']
export const ForsvgTotalImpressions: typeof import("../components/forsvg/TotalImpressions.vue")['default']
export const ForsvgTrafficSource: typeof import("../components/forsvg/TrafficSource.vue")['default']
export const ForsvgTwitter: typeof import("../components/forsvg/Twitter.vue")['default']
export const ForsvgUpColor: typeof import("../components/forsvg/UpColor.vue")['default']
export const ForsvgBookMarkBlank: typeof import("../components/forsvg/bookMarkBlank.vue")['default']
export const ForsvgBookMarkFill: typeof import("../components/forsvg/bookMarkFill.vue")['default']
export const ForsvgClose: typeof import("../components/forsvg/close.vue")['default']
export const ForsvgDelete: typeof import("../components/forsvg/delete.vue")['default']
export const ForsvgDownArrow: typeof import("../components/forsvg/downArrow.vue")['default']
export const ForsvgDownBlank: typeof import("../components/forsvg/downBlank.vue")['default']
export const ForsvgDownFill: typeof import("../components/forsvg/downFill.vue")['default']
export const ForsvgFeedBack: typeof import("../components/forsvg/feedBack.vue")['default']
export const ForsvgGetKeyword: typeof import("../components/forsvg/getKeyword.vue")['default']
export const ForsvgKeywordResearch: typeof import("../components/forsvg/keywordResearch.vue")['default']
export const ForsvgLeftArrow: typeof import("../components/forsvg/leftArrow.vue")['default']
export const ForsvgNotes: typeof import("../components/forsvg/notes.vue")['default']
export const ForsvgPlus: typeof import("../components/forsvg/plus.vue")['default']
export const ForsvgPlusAi: typeof import("../components/forsvg/plusAi.vue")['default']
export const ForsvgQsnMark: typeof import("../components/forsvg/qsnMark.vue")['default']
export const ForsvgRightArrow: typeof import("../components/forsvg/rightArrow.vue")['default']
export const ForsvgUpBlank: typeof import("../components/forsvg/upBlank.vue")['default']
export const ForsvgUpFill: typeof import("../components/forsvg/upFill.vue")['default']
export const ForsvgWorldBlack: typeof import("../components/forsvg/worldBlack.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyOnboardingForm: typeof import("../components/OnboardingForm.vue")['default']
export const LazyAgencyPanelSidebar: typeof import("../components/agency/AgencyPanelSidebar.vue")['default']
export const LazyAgencyTopHeader: typeof import("../components/agency/AgencyTopHeader.vue")['default']
export const LazyAgencyMiniSidebar: typeof import("../components/agency/MiniSidebar.vue")['default']
export const LazyForsvgAdditionalSearchTerms: typeof import("../components/forsvg/AdditionalSearchTerms.vue")['default']
export const LazyForsvgArrowDownIcon: typeof import("../components/forsvg/ArrowDownIcon.vue")['default']
export const LazyForsvgArrowLeftIcon: typeof import("../components/forsvg/ArrowLeftIcon.vue")['default']
export const LazyForsvgArrowRightIcon: typeof import("../components/forsvg/ArrowRightIcon.vue")['default']
export const LazyForsvgArrowUpIcon: typeof import("../components/forsvg/ArrowUpIcon.vue")['default']
export const LazyForsvgArrowUpRight: typeof import("../components/forsvg/ArrowUpRight.vue")['default']
export const LazyForsvgArticaleSuggset: typeof import("../components/forsvg/ArticaleSuggset.vue")['default']
export const LazyForsvgArticle3DotIcon: typeof import("../components/forsvg/Article3DotIcon.vue")['default']
export const LazyForsvgArticleCalenderPen: typeof import("../components/forsvg/ArticleCalenderPen.vue")['default']
export const LazyForsvgArticleChartLineUp: typeof import("../components/forsvg/ArticleChartLineUp.vue")['default']
export const LazyForsvgArticleDraftEditIcon: typeof import("../components/forsvg/ArticleDraftEditIcon.vue")['default']
export const LazyForsvgArticleEditIcon: typeof import("../components/forsvg/ArticleEditIcon.vue")['default']
export const LazyForsvgArticleIcon: typeof import("../components/forsvg/ArticleIcon.vue")['default']
export const LazyForsvgArticleSuggestionIcon: typeof import("../components/forsvg/ArticleSuggestionIcon.vue")['default']
export const LazyForsvgArticleThumbUp: typeof import("../components/forsvg/ArticleThumbUp.vue")['default']
export const LazyForsvgArticleUserCheck: typeof import("../components/forsvg/ArticleUserCheck.vue")['default']
export const LazyForsvgAscendingIcon: typeof import("../components/forsvg/AscendingIcon.vue")['default']
export const LazyForsvgAveragePosition: typeof import("../components/forsvg/AveragePosition.vue")['default']
export const LazyForsvgBellIcon: typeof import("../components/forsvg/BellIcon.vue")['default']
export const LazyForsvgBluebtnSpinner: typeof import("../components/forsvg/BluebtnSpinner.vue")['default']
export const LazyForsvgBook: typeof import("../components/forsvg/Book.vue")['default']
export const LazyForsvgCircleProgress: typeof import("../components/forsvg/CircleProgress.vue")['default']
export const LazyForsvgCircleThreeQuartersStroke: typeof import("../components/forsvg/CircleThreeQuartersStroke.vue")['default']
export const LazyForsvgCross: typeof import("../components/forsvg/Cross.vue")['default']
export const LazyForsvgDashboardIcon: typeof import("../components/forsvg/DashboardIcon.vue")['default']
export const LazyForsvgDeleteIcon: typeof import("../components/forsvg/DeleteIcon.vue")['default']
export const LazyForsvgDescendingIcon: typeof import("../components/forsvg/DescendingIcon.vue")['default']
export const LazyForsvgDownCaret: typeof import("../components/forsvg/DownCaret.vue")['default']
export const LazyForsvgDownDrodown: typeof import("../components/forsvg/DownDrodown.vue")['default']
export const LazyForsvgEditIcon: typeof import("../components/forsvg/EditIcon.vue")['default']
export const LazyForsvgGenerateText: typeof import("../components/forsvg/GenerateText.vue")['default']
export const LazyForsvgHeaderLogo: typeof import("../components/forsvg/HeaderLogo.vue")['default']
export const LazyForsvgKeywords: typeof import("../components/forsvg/Keywords.vue")['default']
export const LazyForsvgLoginBg: typeof import("../components/forsvg/LoginBg.vue")['default']
export const LazyForsvgMainSearchTerms: typeof import("../components/forsvg/MainSearchTerms.vue")['default']
export const LazyForsvgMenuBar: typeof import("../components/forsvg/MenuBar.vue")['default']
export const LazyForsvgMyBlueBtnSpinner: typeof import("../components/forsvg/MyBlueBtnSpinner.vue")['default']
export const LazyForsvgPaperClip: typeof import("../components/forsvg/PaperClip.vue")['default']
export const LazyForsvgPlusIcon: typeof import("../components/forsvg/PlusIcon.vue")['default']
export const LazyForsvgQuestionMark: typeof import("../components/forsvg/QuestionMark.vue")['default']
export const LazyForsvgReasoning: typeof import("../components/forsvg/Reasoning.vue")['default']
export const LazyForsvgReportIcon: typeof import("../components/forsvg/ReportIcon.vue")['default']
export const LazyForsvgRightArrowGo: typeof import("../components/forsvg/RightArrowGo.vue")['default']
export const LazyForsvgRocketBlack: typeof import("../components/forsvg/RocketBlack.vue")['default']
export const LazyForsvgRocketIcon: typeof import("../components/forsvg/RocketIcon.vue")['default']
export const LazyForsvgSageSunglasses: typeof import("../components/forsvg/SageSunglasses.vue")['default']
export const LazyForsvgSearch: typeof import("../components/forsvg/Search.vue")['default']
export const LazyForsvgSeoToolIcon: typeof import("../components/forsvg/SeoToolIcon.vue")['default']
export const LazyForsvgSetting: typeof import("../components/forsvg/Setting.vue")['default']
export const LazyForsvgSpinningWheel: typeof import("../components/forsvg/SpinningWheel.vue")['default']
export const LazyForsvgStar: typeof import("../components/forsvg/Star.vue")['default']
export const LazyForsvgSummary: typeof import("../components/forsvg/Summary.vue")['default']
export const LazyForsvgTbjIcon: typeof import("../components/forsvg/TbjIcon.vue")['default']
export const LazyForsvgThumbsUp: typeof import("../components/forsvg/ThumbsUp.vue")['default']
export const LazyForsvgThumbsUpSolid: typeof import("../components/forsvg/ThumbsUpSolid.vue")['default']
export const LazyForsvgTotalImpressions: typeof import("../components/forsvg/TotalImpressions.vue")['default']
export const LazyForsvgTrafficSource: typeof import("../components/forsvg/TrafficSource.vue")['default']
export const LazyForsvgTwitter: typeof import("../components/forsvg/Twitter.vue")['default']
export const LazyForsvgUpColor: typeof import("../components/forsvg/UpColor.vue")['default']
export const LazyForsvgBookMarkBlank: typeof import("../components/forsvg/bookMarkBlank.vue")['default']
export const LazyForsvgBookMarkFill: typeof import("../components/forsvg/bookMarkFill.vue")['default']
export const LazyForsvgClose: typeof import("../components/forsvg/close.vue")['default']
export const LazyForsvgDelete: typeof import("../components/forsvg/delete.vue")['default']
export const LazyForsvgDownArrow: typeof import("../components/forsvg/downArrow.vue")['default']
export const LazyForsvgDownBlank: typeof import("../components/forsvg/downBlank.vue")['default']
export const LazyForsvgDownFill: typeof import("../components/forsvg/downFill.vue")['default']
export const LazyForsvgFeedBack: typeof import("../components/forsvg/feedBack.vue")['default']
export const LazyForsvgGetKeyword: typeof import("../components/forsvg/getKeyword.vue")['default']
export const LazyForsvgKeywordResearch: typeof import("../components/forsvg/keywordResearch.vue")['default']
export const LazyForsvgLeftArrow: typeof import("../components/forsvg/leftArrow.vue")['default']
export const LazyForsvgNotes: typeof import("../components/forsvg/notes.vue")['default']
export const LazyForsvgPlus: typeof import("../components/forsvg/plus.vue")['default']
export const LazyForsvgPlusAi: typeof import("../components/forsvg/plusAi.vue")['default']
export const LazyForsvgQsnMark: typeof import("../components/forsvg/qsnMark.vue")['default']
export const LazyForsvgRightArrow: typeof import("../components/forsvg/rightArrow.vue")['default']
export const LazyForsvgUpBlank: typeof import("../components/forsvg/upBlank.vue")['default']
export const LazyForsvgUpFill: typeof import("../components/forsvg/upFill.vue")['default']
export const LazyForsvgWorldBlack: typeof import("../components/forsvg/worldBlack.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.5.5_ioredis@5.4.1_magicast@0.3.5_rollup@4.22_d74dvaa2xksiz3c5wpre6aal4e/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
