// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/27/2024, 5:43:06 PM
const configMerger = require("/home/likhon/Desktop/Personal Projects/seo-sage-v3/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5_rollup@4.22.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/likhon/Desktop/Personal Projects/seo-sage-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/plugins/**/*.{js,ts,mjs}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/composables/**/*.{js,ts,mjs}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/utils/**/*.{js,ts,mjs}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/likhon/Desktop/Personal Projects/seo-sage-v3/app.config.{js,ts,mjs}"] }));

module.exports = config
